services:
  - type: web
    name: node-python-deploy
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: TESSERACT_PATH
        value: /usr/bin/tesseract
